### ISSUE TITLE
Installing on Windows with MinGW

### ISSUE THREAD

**Issue by legends2k** [siffiejoe/lua-fltk4lua#6]
I've installed `FLKT` using `CMake` and `MinGW` to a directory. When I try to install the rock thus

```
luarocks install fltk4lua FLTK_DIR=F:/Libs/FLTK
```

I get the following error

```
Installing https://luarocks.org/fltk4lua-0.1-1.src.rock...
Using https://luarocks.org/fltk4lua-0.1-1.src.rock... switching to 'build' mode

Error: Failed initializing build back-end for build type 'cpp': f:\apps\lua\/share/lua/5.3/luarocks\build\cpp.lua:3: attempt to call a nil value (global 'module')
```

I've also tried re-installing the rock `luarocks-build-cpp` to no avail. The MinGW compiler I've is _gcc (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 6.2.0_.

**Comment by legends2k** [comment]
I think I know the issue.  The Lua interpreter I've is version 5.3; doesn't have the function `module` defined.  Lua [5.2 deprecated `module`](http://www.lua.org/manual/5.2/manual.html#8.2).  This issue concers `luarocks-build-cpp` and not `fltk4lua` directly, hence closing.

**Comment by siffiejoe** [comment]
Yes, the situation is known. I have an updated version of luarocks-build-cpp in my repository and in my personal LuaRocks manifest. You can install it via

```
luarocks install --server=http://luarocks.org/manifests/siffiejoe luarocks-build-cpp
```

as is described in the [Wiki](https://github.com/siffiejoe/lua-fltk4lua/wiki/Building).

I've also contacted the original author some time ago, but I've never heard back.
